#!/bin/sh /etc/rc.common
#Init script for udevd

START=30

start() {
    #----------- START the UDEV daemon --------------
    if [ ! -e /run ]; then
        ln -sf /var/run /run
    fi
    /sbin/udevd --daemon &
}

stop() {
    killall udevd
}

